### ISSUE TITLE
Blind Transfer function doesn't work

### ISSUE THREAD

**Issue by Lawbayly** [mondago/ucclient-js-sdk#148]
Been tinkering around with the sample code in example one here:-
https://github.com/mondago/ucclient-sdk-examples/issues

Tried to add a blind transfer button however whilst looking at the obfuscated code I can see a blind Transfer feature within this code, the example code seems unable to reference it.

A part of me wonders if this because of the e.prototype code at the end of the code what with there not being a blindtransfer function included in those functions in the js file.

Any ideas where to go from here, really stretching my mind at this point, I'm using the released zip.

Hah... looks like the method doesn't exist in the "Methods" in the documentation, is it possible to add a blind transfer option?

**Comment by hogsknows2** [comment]
Hi 

At the moment we not extending the V3 API to support Transfers.

V4 API does include further call control methods.
