### ISSUE TITLE
window.ucsdk.default cannot be read 

### ISSUE THREAD

**Issue by roberthantink** [mondago/ucclient-js-sdk#2]
Hello,

First off goodjob so far that there is a JS library. 
However I can't get it to work.
I've added the JS file UCAPI.js to my project and I am trying to create the const by using:

`const UCSession = window.ucsdk.default`

However this results in an error: 

> Uncaught TypeError: Cannot read property 'default' of undefined at <anonymous>:1:32

What am I missing and could you supply some more info in the readme on how to set this up?
What is needed for this to work, I have HIPIN installed on my PC and a working phone connected so I am ready to go.

Greetings from the Netherlands,

Robert

**Comment by ccpdouglas** [comment]
Hi (@roberthantink ),

Thanks for getting in touch. Sorry to hear you're having some issues. Just a quick few questions so we can understand what might be happening.

Are you using vanilla JavaScript and HTML (as in no compilation)?
Can we see the html file you're using to load the library?
And if possible could we see your folder structure as well?

Thanks,
Callum

**Comment by roberthantink** [comment]
Did not expect a comment that quick. I did not use vanilla HTML. We are building a big project using www.outsystems.com which eventually results in HTML. I can point you to a [public site](https://klantenservice-dev.santepartners.nl/RobertHantink/Entry1.aspx?_ts=636939577528395680) where I've added the Library.

**Comment by ccpdouglas** [comment]
Thanks @roberthantink I see the site.

Where have you included the JavaScript library? As a script tag?
And are you including the correct file? I see in your original comment that you're including UCAPI.js, whereas the library resides in ucsdk.js.

**Comment by roberthantink** [comment]
Ah ok wrong library. I'll test it when I am back at my client. Thank you very much.

**Comment by roberthantink** [comment]
I am very happy with this library, because I finally have something to work with in our project that is not build on weird architecture. So thank you for this Library.

However there are still things unclear to me.

1. In this situation I am already logged into HIPIN and also Logged into the phone. I get the following output when running this code:

`const UCSession = window.ucsdk.default

const ucSession = new UCSession()

ucSession.connect()

window.addEventListener("ucLogin", loginEvent => console.log(loginEvent.detail))
window.addEventListener("ucCall", callEvent => console.log(callEvent.detail))`

![ucEventLogin](https://user-images.githubusercontent.com/17430875/58403864-075b0000-8064-11e9-87b5-2a64be26bb4f.png)

Now my question is: Why is everything in the loginEvent.detail empty. Despite the fact that I am succesfully logged in? I Expect to see my login credentials or something here.

2. After this situation I preform a incomming call to the number I am logged into and then hang up. The listeners work and they show me the following log:
![CallEventLog](https://user-images.githubusercontent.com/17430875/58404014-6caef100-8064-11e9-8846-ad191f7e53d0.png)

Why does it send the same "UPDATE" event 3 times? Does this mean this account is logged into the system from 3 different places? 


Greetings,


Robert

**Comment by ccpdouglas** [comment]
Thanks @roberthantink really pleased you're enjoying using the kit.

1. The Login response is the default response from the host application and not the API. This behaviour is under review, if there is a change then the requirement would be to upgrade the Client.

2. Yes this is expected behavior, you're not logged in multiple times, these are just events we're getting from the client updating us and affirming state.
