### ISSUE TITLE
Ucclient Session Connect Null

### ISSUE THREAD

**Issue by Rojina99** [mondago/ucclient-js-sdk#21]
I have connected to uc client with
const UCSession = window.ucsdk.default
const ucSession = new UCSession()
ucSession.connect();

But my parameters of ucclient object returns null value. So, I wanted to how can I connect to client here. Do I have to add password while defining UCSession() object.

Or connecting go integrator in desktop with pbx will connect this session automatically ?

**Comment by hogsknows2** [comment]
Hi

The sdk requires that you have a licensed desktop client running. 
See Dependencies in readme section.

**Comment by Rojina99** [comment]
@hogsknows2 

I saw the dependencies and installed it. But was unsure where in the code it specifies about desktop client because I went through ucsdk.js and ucsdk.js.mirror but could not find the code specifying link to desktop client so. 

Thank You for making it clear.
