### ISSUE TITLE
Uncaught TypeError: Cannot read property 'makeCall' of undefined

### ISSUE THREAD

**Issue by BlommaertsEdwin** [mondago/ucclient-js-sdk#63]
Hello,

While trying the SDK I'm getting the following error as per the title.

`const UCSession = window.ucsdk.default
 const ucSession = new UCSession()
 ucSession.connect()
 window.addEventListener("ucLogin", loginEvent => console.log(loginEvent.detail))
 window.addEventListener("ucCall", callEvent => console.log(callEvent.detail))
 ucSession.callController.makeCall('0123456789')`

I am probably missing something obvious so would appreciate some help.

**Comment by ccpdouglas** [comment]
Hi @BlommaertsEdwin 

From the limited view I have of your situation, it looks like you're not waiting for login properly. 

`callController` will not be set until after login. If you were to make the call inside the login event listener, this should solve your problem.

**Comment by ccpdouglas** [comment]
@BlommaertsEdwin I'm going to close this issue now because of inactivity, I assume this has solved your problem.
